apiVersion: v1
kind: Service
metadata:
  name: signup-app
  namespace: signup-app
spec:
  type: NodePort
  selector:
    app: signup-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
