apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: signup-app
type: Opaque
stringData:
  POSTGRES_DB: signupdb
  POSTGRES_USER: signupuser
  POSTGRES_PASSWORD: signup_password
